// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: employeeSimple.proto

package tcw.domain.protobuf;

public final class EmployeeProtoSimple {
  private EmployeeProtoSimple() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface EmployeeSimpleOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int64 employeeId = 1;
    /**
     * <code>optional int64 employeeId = 1;</code>
     */
    boolean hasEmployeeId();
    /**
     * <code>optional int64 employeeId = 1;</code>
     */
    long getEmployeeId();

    // optional double salery = 2;
    /**
     * <code>optional double salery = 2;</code>
     */
    boolean hasSalery();
    /**
     * <code>optional double salery = 2;</code>
     */
    double getSalery();

    // optional bool consultant = 3;
    /**
     * <code>optional bool consultant = 3;</code>
     */
    boolean hasConsultant();
    /**
     * <code>optional bool consultant = 3;</code>
     */
    boolean getConsultant();

    // optional string employeeName = 4;
    /**
     * <code>optional string employeeName = 4;</code>
     */
    boolean hasEmployeeName();
    /**
     * <code>optional string employeeName = 4;</code>
     */
    java.lang.String getEmployeeName();
    /**
     * <code>optional string employeeName = 4;</code>
     */
    com.google.protobuf.ByteString
        getEmployeeNameBytes();

    // optional string departmentA = 5;
    /**
     * <code>optional string departmentA = 5;</code>
     */
    boolean hasDepartmentA();
    /**
     * <code>optional string departmentA = 5;</code>
     */
    java.lang.String getDepartmentA();
    /**
     * <code>optional string departmentA = 5;</code>
     */
    com.google.protobuf.ByteString
        getDepartmentABytes();

    // optional string departmentB = 6;
    /**
     * <code>optional string departmentB = 6;</code>
     */
    boolean hasDepartmentB();
    /**
     * <code>optional string departmentB = 6;</code>
     */
    java.lang.String getDepartmentB();
    /**
     * <code>optional string departmentB = 6;</code>
     */
    com.google.protobuf.ByteString
        getDepartmentBBytes();

    // optional string departmentC = 7;
    /**
     * <code>optional string departmentC = 7;</code>
     */
    boolean hasDepartmentC();
    /**
     * <code>optional string departmentC = 7;</code>
     */
    java.lang.String getDepartmentC();
    /**
     * <code>optional string departmentC = 7;</code>
     */
    com.google.protobuf.ByteString
        getDepartmentCBytes();
  }
  /**
   * Protobuf type {@code employees.EmployeeSimple}
   */
  public static final class EmployeeSimple extends
      com.google.protobuf.GeneratedMessage
      implements EmployeeSimpleOrBuilder {
    // Use EmployeeSimple.newBuilder() to construct.
    private EmployeeSimple(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private EmployeeSimple(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final EmployeeSimple defaultInstance;
    public static EmployeeSimple getDefaultInstance() {
      return defaultInstance;
    }

    public EmployeeSimple getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private EmployeeSimple(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              employeeId_ = input.readInt64();
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              salery_ = input.readDouble();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              consultant_ = input.readBool();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              employeeName_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              departmentA_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              departmentB_ = input.readBytes();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              departmentC_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return tcw.domain.protobuf.EmployeeProtoSimple.internal_static_employees_EmployeeSimple_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tcw.domain.protobuf.EmployeeProtoSimple.internal_static_employees_EmployeeSimple_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              tcw.domain.protobuf.EmployeeProtoSimple.EmployeeSimple.class, tcw.domain.protobuf.EmployeeProtoSimple.EmployeeSimple.Builder.class);
    }

    public static com.google.protobuf.Parser<EmployeeSimple> PARSER =
        new com.google.protobuf.AbstractParser<EmployeeSimple>() {
      public EmployeeSimple parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EmployeeSimple(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<EmployeeSimple> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int64 employeeId = 1;
    public static final int EMPLOYEEID_FIELD_NUMBER = 1;
    private long employeeId_;
    /**
     * <code>optional int64 employeeId = 1;</code>
     */
    public boolean hasEmployeeId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 employeeId = 1;</code>
     */
    public long getEmployeeId() {
      return employeeId_;
    }

    // optional double salery = 2;
    public static final int SALERY_FIELD_NUMBER = 2;
    private double salery_;
    /**
     * <code>optional double salery = 2;</code>
     */
    public boolean hasSalery() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional double salery = 2;</code>
     */
    public double getSalery() {
      return salery_;
    }

    // optional bool consultant = 3;
    public static final int CONSULTANT_FIELD_NUMBER = 3;
    private boolean consultant_;
    /**
     * <code>optional bool consultant = 3;</code>
     */
    public boolean hasConsultant() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bool consultant = 3;</code>
     */
    public boolean getConsultant() {
      return consultant_;
    }

    // optional string employeeName = 4;
    public static final int EMPLOYEENAME_FIELD_NUMBER = 4;
    private java.lang.Object employeeName_;
    /**
     * <code>optional string employeeName = 4;</code>
     */
    public boolean hasEmployeeName() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string employeeName = 4;</code>
     */
    public java.lang.String getEmployeeName() {
      java.lang.Object ref = employeeName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          employeeName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string employeeName = 4;</code>
     */
    public com.google.protobuf.ByteString
        getEmployeeNameBytes() {
      java.lang.Object ref = employeeName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        employeeName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string departmentA = 5;
    public static final int DEPARTMENTA_FIELD_NUMBER = 5;
    private java.lang.Object departmentA_;
    /**
     * <code>optional string departmentA = 5;</code>
     */
    public boolean hasDepartmentA() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string departmentA = 5;</code>
     */
    public java.lang.String getDepartmentA() {
      java.lang.Object ref = departmentA_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          departmentA_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string departmentA = 5;</code>
     */
    public com.google.protobuf.ByteString
        getDepartmentABytes() {
      java.lang.Object ref = departmentA_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        departmentA_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string departmentB = 6;
    public static final int DEPARTMENTB_FIELD_NUMBER = 6;
    private java.lang.Object departmentB_;
    /**
     * <code>optional string departmentB = 6;</code>
     */
    public boolean hasDepartmentB() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string departmentB = 6;</code>
     */
    public java.lang.String getDepartmentB() {
      java.lang.Object ref = departmentB_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          departmentB_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string departmentB = 6;</code>
     */
    public com.google.protobuf.ByteString
        getDepartmentBBytes() {
      java.lang.Object ref = departmentB_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        departmentB_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string departmentC = 7;
    public static final int DEPARTMENTC_FIELD_NUMBER = 7;
    private java.lang.Object departmentC_;
    /**
     * <code>optional string departmentC = 7;</code>
     */
    public boolean hasDepartmentC() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string departmentC = 7;</code>
     */
    public java.lang.String getDepartmentC() {
      java.lang.Object ref = departmentC_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          departmentC_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string departmentC = 7;</code>
     */
    public com.google.protobuf.ByteString
        getDepartmentCBytes() {
      java.lang.Object ref = departmentC_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        departmentC_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      employeeId_ = 0L;
      salery_ = 0D;
      consultant_ = false;
      employeeName_ = "";
      departmentA_ = "";
      departmentB_ = "";
      departmentC_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, employeeId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeDouble(2, salery_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBool(3, consultant_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getEmployeeNameBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getDepartmentABytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getDepartmentBBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getDepartmentCBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, employeeId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, salery_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, consultant_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getEmployeeNameBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getDepartmentABytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getDepartmentBBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getDepartmentCBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static tcw.domain.protobuf.EmployeeProtoSimple.EmployeeSimple parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tcw.domain.protobuf.EmployeeProtoSimple.EmployeeSimple parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tcw.domain.protobuf.EmployeeProtoSimple.EmployeeSimple parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tcw.domain.protobuf.EmployeeProtoSimple.EmployeeSimple parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tcw.domain.protobuf.EmployeeProtoSimple.EmployeeSimple parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static tcw.domain.protobuf.EmployeeProtoSimple.EmployeeSimple parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static tcw.domain.protobuf.EmployeeProtoSimple.EmployeeSimple parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static tcw.domain.protobuf.EmployeeProtoSimple.EmployeeSimple parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static tcw.domain.protobuf.EmployeeProtoSimple.EmployeeSimple parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static tcw.domain.protobuf.EmployeeProtoSimple.EmployeeSimple parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(tcw.domain.protobuf.EmployeeProtoSimple.EmployeeSimple prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code employees.EmployeeSimple}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements tcw.domain.protobuf.EmployeeProtoSimple.EmployeeSimpleOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return tcw.domain.protobuf.EmployeeProtoSimple.internal_static_employees_EmployeeSimple_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return tcw.domain.protobuf.EmployeeProtoSimple.internal_static_employees_EmployeeSimple_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                tcw.domain.protobuf.EmployeeProtoSimple.EmployeeSimple.class, tcw.domain.protobuf.EmployeeProtoSimple.EmployeeSimple.Builder.class);
      }

      // Construct using tcw.domain.protobuf.EmployeeProtoSimple.EmployeeSimple.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        employeeId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        salery_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000002);
        consultant_ = false;
        bitField0_ = (bitField0_ & ~0x00000004);
        employeeName_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        departmentA_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        departmentB_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        departmentC_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return tcw.domain.protobuf.EmployeeProtoSimple.internal_static_employees_EmployeeSimple_descriptor;
      }

      public tcw.domain.protobuf.EmployeeProtoSimple.EmployeeSimple getDefaultInstanceForType() {
        return tcw.domain.protobuf.EmployeeProtoSimple.EmployeeSimple.getDefaultInstance();
      }

      public tcw.domain.protobuf.EmployeeProtoSimple.EmployeeSimple build() {
        tcw.domain.protobuf.EmployeeProtoSimple.EmployeeSimple result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public tcw.domain.protobuf.EmployeeProtoSimple.EmployeeSimple buildPartial() {
        tcw.domain.protobuf.EmployeeProtoSimple.EmployeeSimple result = new tcw.domain.protobuf.EmployeeProtoSimple.EmployeeSimple(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.employeeId_ = employeeId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.salery_ = salery_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.consultant_ = consultant_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.employeeName_ = employeeName_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.departmentA_ = departmentA_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.departmentB_ = departmentB_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.departmentC_ = departmentC_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof tcw.domain.protobuf.EmployeeProtoSimple.EmployeeSimple) {
          return mergeFrom((tcw.domain.protobuf.EmployeeProtoSimple.EmployeeSimple)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(tcw.domain.protobuf.EmployeeProtoSimple.EmployeeSimple other) {
        if (other == tcw.domain.protobuf.EmployeeProtoSimple.EmployeeSimple.getDefaultInstance()) return this;
        if (other.hasEmployeeId()) {
          setEmployeeId(other.getEmployeeId());
        }
        if (other.hasSalery()) {
          setSalery(other.getSalery());
        }
        if (other.hasConsultant()) {
          setConsultant(other.getConsultant());
        }
        if (other.hasEmployeeName()) {
          bitField0_ |= 0x00000008;
          employeeName_ = other.employeeName_;
          onChanged();
        }
        if (other.hasDepartmentA()) {
          bitField0_ |= 0x00000010;
          departmentA_ = other.departmentA_;
          onChanged();
        }
        if (other.hasDepartmentB()) {
          bitField0_ |= 0x00000020;
          departmentB_ = other.departmentB_;
          onChanged();
        }
        if (other.hasDepartmentC()) {
          bitField0_ |= 0x00000040;
          departmentC_ = other.departmentC_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        tcw.domain.protobuf.EmployeeProtoSimple.EmployeeSimple parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (tcw.domain.protobuf.EmployeeProtoSimple.EmployeeSimple) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int64 employeeId = 1;
      private long employeeId_ ;
      /**
       * <code>optional int64 employeeId = 1;</code>
       */
      public boolean hasEmployeeId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 employeeId = 1;</code>
       */
      public long getEmployeeId() {
        return employeeId_;
      }
      /**
       * <code>optional int64 employeeId = 1;</code>
       */
      public Builder setEmployeeId(long value) {
        bitField0_ |= 0x00000001;
        employeeId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 employeeId = 1;</code>
       */
      public Builder clearEmployeeId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        employeeId_ = 0L;
        onChanged();
        return this;
      }

      // optional double salery = 2;
      private double salery_ ;
      /**
       * <code>optional double salery = 2;</code>
       */
      public boolean hasSalery() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional double salery = 2;</code>
       */
      public double getSalery() {
        return salery_;
      }
      /**
       * <code>optional double salery = 2;</code>
       */
      public Builder setSalery(double value) {
        bitField0_ |= 0x00000002;
        salery_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double salery = 2;</code>
       */
      public Builder clearSalery() {
        bitField0_ = (bitField0_ & ~0x00000002);
        salery_ = 0D;
        onChanged();
        return this;
      }

      // optional bool consultant = 3;
      private boolean consultant_ ;
      /**
       * <code>optional bool consultant = 3;</code>
       */
      public boolean hasConsultant() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bool consultant = 3;</code>
       */
      public boolean getConsultant() {
        return consultant_;
      }
      /**
       * <code>optional bool consultant = 3;</code>
       */
      public Builder setConsultant(boolean value) {
        bitField0_ |= 0x00000004;
        consultant_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool consultant = 3;</code>
       */
      public Builder clearConsultant() {
        bitField0_ = (bitField0_ & ~0x00000004);
        consultant_ = false;
        onChanged();
        return this;
      }

      // optional string employeeName = 4;
      private java.lang.Object employeeName_ = "";
      /**
       * <code>optional string employeeName = 4;</code>
       */
      public boolean hasEmployeeName() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string employeeName = 4;</code>
       */
      public java.lang.String getEmployeeName() {
        java.lang.Object ref = employeeName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          employeeName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string employeeName = 4;</code>
       */
      public com.google.protobuf.ByteString
          getEmployeeNameBytes() {
        java.lang.Object ref = employeeName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          employeeName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string employeeName = 4;</code>
       */
      public Builder setEmployeeName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        employeeName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string employeeName = 4;</code>
       */
      public Builder clearEmployeeName() {
        bitField0_ = (bitField0_ & ~0x00000008);
        employeeName_ = getDefaultInstance().getEmployeeName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string employeeName = 4;</code>
       */
      public Builder setEmployeeNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        employeeName_ = value;
        onChanged();
        return this;
      }

      // optional string departmentA = 5;
      private java.lang.Object departmentA_ = "";
      /**
       * <code>optional string departmentA = 5;</code>
       */
      public boolean hasDepartmentA() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string departmentA = 5;</code>
       */
      public java.lang.String getDepartmentA() {
        java.lang.Object ref = departmentA_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          departmentA_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string departmentA = 5;</code>
       */
      public com.google.protobuf.ByteString
          getDepartmentABytes() {
        java.lang.Object ref = departmentA_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          departmentA_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string departmentA = 5;</code>
       */
      public Builder setDepartmentA(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        departmentA_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string departmentA = 5;</code>
       */
      public Builder clearDepartmentA() {
        bitField0_ = (bitField0_ & ~0x00000010);
        departmentA_ = getDefaultInstance().getDepartmentA();
        onChanged();
        return this;
      }
      /**
       * <code>optional string departmentA = 5;</code>
       */
      public Builder setDepartmentABytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        departmentA_ = value;
        onChanged();
        return this;
      }

      // optional string departmentB = 6;
      private java.lang.Object departmentB_ = "";
      /**
       * <code>optional string departmentB = 6;</code>
       */
      public boolean hasDepartmentB() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string departmentB = 6;</code>
       */
      public java.lang.String getDepartmentB() {
        java.lang.Object ref = departmentB_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          departmentB_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string departmentB = 6;</code>
       */
      public com.google.protobuf.ByteString
          getDepartmentBBytes() {
        java.lang.Object ref = departmentB_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          departmentB_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string departmentB = 6;</code>
       */
      public Builder setDepartmentB(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        departmentB_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string departmentB = 6;</code>
       */
      public Builder clearDepartmentB() {
        bitField0_ = (bitField0_ & ~0x00000020);
        departmentB_ = getDefaultInstance().getDepartmentB();
        onChanged();
        return this;
      }
      /**
       * <code>optional string departmentB = 6;</code>
       */
      public Builder setDepartmentBBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        departmentB_ = value;
        onChanged();
        return this;
      }

      // optional string departmentC = 7;
      private java.lang.Object departmentC_ = "";
      /**
       * <code>optional string departmentC = 7;</code>
       */
      public boolean hasDepartmentC() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional string departmentC = 7;</code>
       */
      public java.lang.String getDepartmentC() {
        java.lang.Object ref = departmentC_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          departmentC_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string departmentC = 7;</code>
       */
      public com.google.protobuf.ByteString
          getDepartmentCBytes() {
        java.lang.Object ref = departmentC_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          departmentC_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string departmentC = 7;</code>
       */
      public Builder setDepartmentC(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        departmentC_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string departmentC = 7;</code>
       */
      public Builder clearDepartmentC() {
        bitField0_ = (bitField0_ & ~0x00000040);
        departmentC_ = getDefaultInstance().getDepartmentC();
        onChanged();
        return this;
      }
      /**
       * <code>optional string departmentC = 7;</code>
       */
      public Builder setDepartmentCBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        departmentC_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:employees.EmployeeSimple)
    }

    static {
      defaultInstance = new EmployeeSimple(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:employees.EmployeeSimple)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_employees_EmployeeSimple_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_employees_EmployeeSimple_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024employeeSimple.proto\022\temployees\"\235\001\n\016Em" +
      "ployeeSimple\022\022\n\nemployeeId\030\001 \001(\003\022\016\n\006sale" +
      "ry\030\002 \001(\001\022\022\n\nconsultant\030\003 \001(\010\022\024\n\014employee" +
      "Name\030\004 \001(\t\022\023\n\013departmentA\030\005 \001(\t\022\023\n\013depar" +
      "tmentB\030\006 \001(\t\022\023\n\013departmentC\030\007 \001(\tB*\n\023tcw" +
      ".domain.protobufB\023EmployeeProtoSimple"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_employees_EmployeeSimple_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_employees_EmployeeSimple_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_employees_EmployeeSimple_descriptor,
              new java.lang.String[] { "EmployeeId", "Salery", "Consultant", "EmployeeName", "DepartmentA", "DepartmentB", "DepartmentC", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
