// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: employee.proto

package tcw.domain.protobuf;

public final class EmployeeProto {
  private EmployeeProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface EmployeeProtobufOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 employeeId = 1;
    /**
     * <code>required int32 employeeId = 1;</code>
     */
    boolean hasEmployeeId();
    /**
     * <code>required int32 employeeId = 1;</code>
     */
    int getEmployeeId();

    // required string employeeName = 2;
    /**
     * <code>required string employeeName = 2;</code>
     */
    boolean hasEmployeeName();
    /**
     * <code>required string employeeName = 2;</code>
     */
    java.lang.String getEmployeeName();
    /**
     * <code>required string employeeName = 2;</code>
     */
    com.google.protobuf.ByteString
        getEmployeeNameBytes();

    // optional string department = 3;
    /**
     * <code>optional string department = 3;</code>
     */
    boolean hasDepartment();
    /**
     * <code>optional string department = 3;</code>
     */
    java.lang.String getDepartment();
    /**
     * <code>optional string department = 3;</code>
     */
    com.google.protobuf.ByteString
        getDepartmentBytes();

    // repeated .employees.EmployeeProtobuf.Address address = 4;
    /**
     * <code>repeated .employees.EmployeeProtobuf.Address address = 4;</code>
     */
    java.util.List<tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf.Address> 
        getAddressList();
    /**
     * <code>repeated .employees.EmployeeProtobuf.Address address = 4;</code>
     */
    tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf.Address getAddress(int index);
    /**
     * <code>repeated .employees.EmployeeProtobuf.Address address = 4;</code>
     */
    int getAddressCount();
    /**
     * <code>repeated .employees.EmployeeProtobuf.Address address = 4;</code>
     */
    java.util.List<? extends tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf.AddressOrBuilder> 
        getAddressOrBuilderList();
    /**
     * <code>repeated .employees.EmployeeProtobuf.Address address = 4;</code>
     */
    tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf.AddressOrBuilder getAddressOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code employees.EmployeeProtobuf}
   */
  public static final class EmployeeProtobuf extends
      com.google.protobuf.GeneratedMessage
      implements EmployeeProtobufOrBuilder {
    // Use EmployeeProtobuf.newBuilder() to construct.
    private EmployeeProtobuf(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private EmployeeProtobuf(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final EmployeeProtobuf defaultInstance;
    public static EmployeeProtobuf getDefaultInstance() {
      return defaultInstance;
    }

    public EmployeeProtobuf getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private EmployeeProtobuf(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              employeeId_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              employeeName_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              department_ = input.readBytes();
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                address_ = new java.util.ArrayList<tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf.Address>();
                mutable_bitField0_ |= 0x00000008;
              }
              address_.add(input.readMessage(tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf.Address.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          address_ = java.util.Collections.unmodifiableList(address_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return tcw.domain.protobuf.EmployeeProto.internal_static_employees_EmployeeProtobuf_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tcw.domain.protobuf.EmployeeProto.internal_static_employees_EmployeeProtobuf_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf.class, tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf.Builder.class);
    }

    public static com.google.protobuf.Parser<EmployeeProtobuf> PARSER =
        new com.google.protobuf.AbstractParser<EmployeeProtobuf>() {
      public EmployeeProtobuf parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EmployeeProtobuf(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<EmployeeProtobuf> getParserForType() {
      return PARSER;
    }

    public interface AddressOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // required int32 homeNo = 1;
      /**
       * <code>required int32 homeNo = 1;</code>
       */
      boolean hasHomeNo();
      /**
       * <code>required int32 homeNo = 1;</code>
       */
      int getHomeNo();

      // required string street = 2;
      /**
       * <code>required string street = 2;</code>
       */
      boolean hasStreet();
      /**
       * <code>required string street = 2;</code>
       */
      java.lang.String getStreet();
      /**
       * <code>required string street = 2;</code>
       */
      com.google.protobuf.ByteString
          getStreetBytes();

      // required string city = 3;
      /**
       * <code>required string city = 3;</code>
       */
      boolean hasCity();
      /**
       * <code>required string city = 3;</code>
       */
      java.lang.String getCity();
      /**
       * <code>required string city = 3;</code>
       */
      com.google.protobuf.ByteString
          getCityBytes();
    }
    /**
     * Protobuf type {@code employees.EmployeeProtobuf.Address}
     */
    public static final class Address extends
        com.google.protobuf.GeneratedMessage
        implements AddressOrBuilder {
      // Use Address.newBuilder() to construct.
      private Address(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Address(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Address defaultInstance;
      public static Address getDefaultInstance() {
        return defaultInstance;
      }

      public Address getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private Address(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                homeNo_ = input.readInt32();
                break;
              }
              case 18: {
                bitField0_ |= 0x00000002;
                street_ = input.readBytes();
                break;
              }
              case 26: {
                bitField0_ |= 0x00000004;
                city_ = input.readBytes();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return tcw.domain.protobuf.EmployeeProto.internal_static_employees_EmployeeProtobuf_Address_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return tcw.domain.protobuf.EmployeeProto.internal_static_employees_EmployeeProtobuf_Address_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf.Address.class, tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf.Address.Builder.class);
      }

      public static com.google.protobuf.Parser<Address> PARSER =
          new com.google.protobuf.AbstractParser<Address>() {
        public Address parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Address(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<Address> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // required int32 homeNo = 1;
      public static final int HOMENO_FIELD_NUMBER = 1;
      private int homeNo_;
      /**
       * <code>required int32 homeNo = 1;</code>
       */
      public boolean hasHomeNo() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 homeNo = 1;</code>
       */
      public int getHomeNo() {
        return homeNo_;
      }

      // required string street = 2;
      public static final int STREET_FIELD_NUMBER = 2;
      private java.lang.Object street_;
      /**
       * <code>required string street = 2;</code>
       */
      public boolean hasStreet() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string street = 2;</code>
       */
      public java.lang.String getStreet() {
        java.lang.Object ref = street_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            street_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string street = 2;</code>
       */
      public com.google.protobuf.ByteString
          getStreetBytes() {
        java.lang.Object ref = street_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          street_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // required string city = 3;
      public static final int CITY_FIELD_NUMBER = 3;
      private java.lang.Object city_;
      /**
       * <code>required string city = 3;</code>
       */
      public boolean hasCity() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string city = 3;</code>
       */
      public java.lang.String getCity() {
        java.lang.Object ref = city_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            city_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string city = 3;</code>
       */
      public com.google.protobuf.ByteString
          getCityBytes() {
        java.lang.Object ref = city_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          city_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private void initFields() {
        homeNo_ = 0;
        street_ = "";
        city_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasHomeNo()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasStreet()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasCity()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeInt32(1, homeNo_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getStreetBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeBytes(3, getCityBytes());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, homeNo_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getStreetBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(3, getCityBytes());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf.Address parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf.Address parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf.Address parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf.Address parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf.Address parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf.Address parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf.Address parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf.Address parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf.Address parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf.Address parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf.Address prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code employees.EmployeeProtobuf.Address}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf.AddressOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return tcw.domain.protobuf.EmployeeProto.internal_static_employees_EmployeeProtobuf_Address_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return tcw.domain.protobuf.EmployeeProto.internal_static_employees_EmployeeProtobuf_Address_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf.Address.class, tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf.Address.Builder.class);
        }

        // Construct using tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf.Address.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          homeNo_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          street_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          city_ = "";
          bitField0_ = (bitField0_ & ~0x00000004);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return tcw.domain.protobuf.EmployeeProto.internal_static_employees_EmployeeProtobuf_Address_descriptor;
        }

        public tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf.Address getDefaultInstanceForType() {
          return tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf.Address.getDefaultInstance();
        }

        public tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf.Address build() {
          tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf.Address result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf.Address buildPartial() {
          tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf.Address result = new tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf.Address(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.homeNo_ = homeNo_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.street_ = street_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.city_ = city_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf.Address) {
            return mergeFrom((tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf.Address)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf.Address other) {
          if (other == tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf.Address.getDefaultInstance()) return this;
          if (other.hasHomeNo()) {
            setHomeNo(other.getHomeNo());
          }
          if (other.hasStreet()) {
            bitField0_ |= 0x00000002;
            street_ = other.street_;
            onChanged();
          }
          if (other.hasCity()) {
            bitField0_ |= 0x00000004;
            city_ = other.city_;
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasHomeNo()) {
            
            return false;
          }
          if (!hasStreet()) {
            
            return false;
          }
          if (!hasCity()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf.Address parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf.Address) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // required int32 homeNo = 1;
        private int homeNo_ ;
        /**
         * <code>required int32 homeNo = 1;</code>
         */
        public boolean hasHomeNo() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required int32 homeNo = 1;</code>
         */
        public int getHomeNo() {
          return homeNo_;
        }
        /**
         * <code>required int32 homeNo = 1;</code>
         */
        public Builder setHomeNo(int value) {
          bitField0_ |= 0x00000001;
          homeNo_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int32 homeNo = 1;</code>
         */
        public Builder clearHomeNo() {
          bitField0_ = (bitField0_ & ~0x00000001);
          homeNo_ = 0;
          onChanged();
          return this;
        }

        // required string street = 2;
        private java.lang.Object street_ = "";
        /**
         * <code>required string street = 2;</code>
         */
        public boolean hasStreet() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required string street = 2;</code>
         */
        public java.lang.String getStreet() {
          java.lang.Object ref = street_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            street_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string street = 2;</code>
         */
        public com.google.protobuf.ByteString
            getStreetBytes() {
          java.lang.Object ref = street_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            street_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string street = 2;</code>
         */
        public Builder setStreet(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          street_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string street = 2;</code>
         */
        public Builder clearStreet() {
          bitField0_ = (bitField0_ & ~0x00000002);
          street_ = getDefaultInstance().getStreet();
          onChanged();
          return this;
        }
        /**
         * <code>required string street = 2;</code>
         */
        public Builder setStreetBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          street_ = value;
          onChanged();
          return this;
        }

        // required string city = 3;
        private java.lang.Object city_ = "";
        /**
         * <code>required string city = 3;</code>
         */
        public boolean hasCity() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>required string city = 3;</code>
         */
        public java.lang.String getCity() {
          java.lang.Object ref = city_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            city_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string city = 3;</code>
         */
        public com.google.protobuf.ByteString
            getCityBytes() {
          java.lang.Object ref = city_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            city_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string city = 3;</code>
         */
        public Builder setCity(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          city_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string city = 3;</code>
         */
        public Builder clearCity() {
          bitField0_ = (bitField0_ & ~0x00000004);
          city_ = getDefaultInstance().getCity();
          onChanged();
          return this;
        }
        /**
         * <code>required string city = 3;</code>
         */
        public Builder setCityBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          city_ = value;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:employees.EmployeeProtobuf.Address)
      }

      static {
        defaultInstance = new Address(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:employees.EmployeeProtobuf.Address)
    }

    private int bitField0_;
    // required int32 employeeId = 1;
    public static final int EMPLOYEEID_FIELD_NUMBER = 1;
    private int employeeId_;
    /**
     * <code>required int32 employeeId = 1;</code>
     */
    public boolean hasEmployeeId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 employeeId = 1;</code>
     */
    public int getEmployeeId() {
      return employeeId_;
    }

    // required string employeeName = 2;
    public static final int EMPLOYEENAME_FIELD_NUMBER = 2;
    private java.lang.Object employeeName_;
    /**
     * <code>required string employeeName = 2;</code>
     */
    public boolean hasEmployeeName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string employeeName = 2;</code>
     */
    public java.lang.String getEmployeeName() {
      java.lang.Object ref = employeeName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          employeeName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string employeeName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getEmployeeNameBytes() {
      java.lang.Object ref = employeeName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        employeeName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string department = 3;
    public static final int DEPARTMENT_FIELD_NUMBER = 3;
    private java.lang.Object department_;
    /**
     * <code>optional string department = 3;</code>
     */
    public boolean hasDepartment() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string department = 3;</code>
     */
    public java.lang.String getDepartment() {
      java.lang.Object ref = department_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          department_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string department = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDepartmentBytes() {
      java.lang.Object ref = department_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        department_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated .employees.EmployeeProtobuf.Address address = 4;
    public static final int ADDRESS_FIELD_NUMBER = 4;
    private java.util.List<tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf.Address> address_;
    /**
     * <code>repeated .employees.EmployeeProtobuf.Address address = 4;</code>
     */
    public java.util.List<tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf.Address> getAddressList() {
      return address_;
    }
    /**
     * <code>repeated .employees.EmployeeProtobuf.Address address = 4;</code>
     */
    public java.util.List<? extends tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf.AddressOrBuilder> 
        getAddressOrBuilderList() {
      return address_;
    }
    /**
     * <code>repeated .employees.EmployeeProtobuf.Address address = 4;</code>
     */
    public int getAddressCount() {
      return address_.size();
    }
    /**
     * <code>repeated .employees.EmployeeProtobuf.Address address = 4;</code>
     */
    public tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf.Address getAddress(int index) {
      return address_.get(index);
    }
    /**
     * <code>repeated .employees.EmployeeProtobuf.Address address = 4;</code>
     */
    public tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf.AddressOrBuilder getAddressOrBuilder(
        int index) {
      return address_.get(index);
    }

    private void initFields() {
      employeeId_ = 0;
      employeeName_ = "";
      department_ = "";
      address_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasEmployeeId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEmployeeName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getAddressCount(); i++) {
        if (!getAddress(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, employeeId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getEmployeeNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getDepartmentBytes());
      }
      for (int i = 0; i < address_.size(); i++) {
        output.writeMessage(4, address_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, employeeId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getEmployeeNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getDepartmentBytes());
      }
      for (int i = 0; i < address_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, address_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code employees.EmployeeProtobuf}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements tcw.domain.protobuf.EmployeeProto.EmployeeProtobufOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return tcw.domain.protobuf.EmployeeProto.internal_static_employees_EmployeeProtobuf_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return tcw.domain.protobuf.EmployeeProto.internal_static_employees_EmployeeProtobuf_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf.class, tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf.Builder.class);
      }

      // Construct using tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getAddressFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        employeeId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        employeeName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        department_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        if (addressBuilder_ == null) {
          address_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          addressBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return tcw.domain.protobuf.EmployeeProto.internal_static_employees_EmployeeProtobuf_descriptor;
      }

      public tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf getDefaultInstanceForType() {
        return tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf.getDefaultInstance();
      }

      public tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf build() {
        tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf buildPartial() {
        tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf result = new tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.employeeId_ = employeeId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.employeeName_ = employeeName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.department_ = department_;
        if (addressBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            address_ = java.util.Collections.unmodifiableList(address_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.address_ = address_;
        } else {
          result.address_ = addressBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf) {
          return mergeFrom((tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf other) {
        if (other == tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf.getDefaultInstance()) return this;
        if (other.hasEmployeeId()) {
          setEmployeeId(other.getEmployeeId());
        }
        if (other.hasEmployeeName()) {
          bitField0_ |= 0x00000002;
          employeeName_ = other.employeeName_;
          onChanged();
        }
        if (other.hasDepartment()) {
          bitField0_ |= 0x00000004;
          department_ = other.department_;
          onChanged();
        }
        if (addressBuilder_ == null) {
          if (!other.address_.isEmpty()) {
            if (address_.isEmpty()) {
              address_ = other.address_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureAddressIsMutable();
              address_.addAll(other.address_);
            }
            onChanged();
          }
        } else {
          if (!other.address_.isEmpty()) {
            if (addressBuilder_.isEmpty()) {
              addressBuilder_.dispose();
              addressBuilder_ = null;
              address_ = other.address_;
              bitField0_ = (bitField0_ & ~0x00000008);
              addressBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getAddressFieldBuilder() : null;
            } else {
              addressBuilder_.addAllMessages(other.address_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasEmployeeId()) {
          
          return false;
        }
        if (!hasEmployeeName()) {
          
          return false;
        }
        for (int i = 0; i < getAddressCount(); i++) {
          if (!getAddress(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 employeeId = 1;
      private int employeeId_ ;
      /**
       * <code>required int32 employeeId = 1;</code>
       */
      public boolean hasEmployeeId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 employeeId = 1;</code>
       */
      public int getEmployeeId() {
        return employeeId_;
      }
      /**
       * <code>required int32 employeeId = 1;</code>
       */
      public Builder setEmployeeId(int value) {
        bitField0_ |= 0x00000001;
        employeeId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 employeeId = 1;</code>
       */
      public Builder clearEmployeeId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        employeeId_ = 0;
        onChanged();
        return this;
      }

      // required string employeeName = 2;
      private java.lang.Object employeeName_ = "";
      /**
       * <code>required string employeeName = 2;</code>
       */
      public boolean hasEmployeeName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string employeeName = 2;</code>
       */
      public java.lang.String getEmployeeName() {
        java.lang.Object ref = employeeName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          employeeName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string employeeName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getEmployeeNameBytes() {
        java.lang.Object ref = employeeName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          employeeName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string employeeName = 2;</code>
       */
      public Builder setEmployeeName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        employeeName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string employeeName = 2;</code>
       */
      public Builder clearEmployeeName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        employeeName_ = getDefaultInstance().getEmployeeName();
        onChanged();
        return this;
      }
      /**
       * <code>required string employeeName = 2;</code>
       */
      public Builder setEmployeeNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        employeeName_ = value;
        onChanged();
        return this;
      }

      // optional string department = 3;
      private java.lang.Object department_ = "";
      /**
       * <code>optional string department = 3;</code>
       */
      public boolean hasDepartment() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string department = 3;</code>
       */
      public java.lang.String getDepartment() {
        java.lang.Object ref = department_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          department_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string department = 3;</code>
       */
      public com.google.protobuf.ByteString
          getDepartmentBytes() {
        java.lang.Object ref = department_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          department_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string department = 3;</code>
       */
      public Builder setDepartment(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        department_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string department = 3;</code>
       */
      public Builder clearDepartment() {
        bitField0_ = (bitField0_ & ~0x00000004);
        department_ = getDefaultInstance().getDepartment();
        onChanged();
        return this;
      }
      /**
       * <code>optional string department = 3;</code>
       */
      public Builder setDepartmentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        department_ = value;
        onChanged();
        return this;
      }

      // repeated .employees.EmployeeProtobuf.Address address = 4;
      private java.util.List<tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf.Address> address_ =
        java.util.Collections.emptyList();
      private void ensureAddressIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          address_ = new java.util.ArrayList<tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf.Address>(address_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf.Address, tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf.Address.Builder, tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf.AddressOrBuilder> addressBuilder_;

      /**
       * <code>repeated .employees.EmployeeProtobuf.Address address = 4;</code>
       */
      public java.util.List<tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf.Address> getAddressList() {
        if (addressBuilder_ == null) {
          return java.util.Collections.unmodifiableList(address_);
        } else {
          return addressBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .employees.EmployeeProtobuf.Address address = 4;</code>
       */
      public int getAddressCount() {
        if (addressBuilder_ == null) {
          return address_.size();
        } else {
          return addressBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .employees.EmployeeProtobuf.Address address = 4;</code>
       */
      public tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf.Address getAddress(int index) {
        if (addressBuilder_ == null) {
          return address_.get(index);
        } else {
          return addressBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .employees.EmployeeProtobuf.Address address = 4;</code>
       */
      public Builder setAddress(
          int index, tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf.Address value) {
        if (addressBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAddressIsMutable();
          address_.set(index, value);
          onChanged();
        } else {
          addressBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .employees.EmployeeProtobuf.Address address = 4;</code>
       */
      public Builder setAddress(
          int index, tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf.Address.Builder builderForValue) {
        if (addressBuilder_ == null) {
          ensureAddressIsMutable();
          address_.set(index, builderForValue.build());
          onChanged();
        } else {
          addressBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .employees.EmployeeProtobuf.Address address = 4;</code>
       */
      public Builder addAddress(tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf.Address value) {
        if (addressBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAddressIsMutable();
          address_.add(value);
          onChanged();
        } else {
          addressBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .employees.EmployeeProtobuf.Address address = 4;</code>
       */
      public Builder addAddress(
          int index, tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf.Address value) {
        if (addressBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAddressIsMutable();
          address_.add(index, value);
          onChanged();
        } else {
          addressBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .employees.EmployeeProtobuf.Address address = 4;</code>
       */
      public Builder addAddress(
          tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf.Address.Builder builderForValue) {
        if (addressBuilder_ == null) {
          ensureAddressIsMutable();
          address_.add(builderForValue.build());
          onChanged();
        } else {
          addressBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .employees.EmployeeProtobuf.Address address = 4;</code>
       */
      public Builder addAddress(
          int index, tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf.Address.Builder builderForValue) {
        if (addressBuilder_ == null) {
          ensureAddressIsMutable();
          address_.add(index, builderForValue.build());
          onChanged();
        } else {
          addressBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .employees.EmployeeProtobuf.Address address = 4;</code>
       */
      public Builder addAllAddress(
          java.lang.Iterable<? extends tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf.Address> values) {
        if (addressBuilder_ == null) {
          ensureAddressIsMutable();
          super.addAll(values, address_);
          onChanged();
        } else {
          addressBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .employees.EmployeeProtobuf.Address address = 4;</code>
       */
      public Builder clearAddress() {
        if (addressBuilder_ == null) {
          address_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          addressBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .employees.EmployeeProtobuf.Address address = 4;</code>
       */
      public Builder removeAddress(int index) {
        if (addressBuilder_ == null) {
          ensureAddressIsMutable();
          address_.remove(index);
          onChanged();
        } else {
          addressBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .employees.EmployeeProtobuf.Address address = 4;</code>
       */
      public tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf.Address.Builder getAddressBuilder(
          int index) {
        return getAddressFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .employees.EmployeeProtobuf.Address address = 4;</code>
       */
      public tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf.AddressOrBuilder getAddressOrBuilder(
          int index) {
        if (addressBuilder_ == null) {
          return address_.get(index);  } else {
          return addressBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .employees.EmployeeProtobuf.Address address = 4;</code>
       */
      public java.util.List<? extends tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf.AddressOrBuilder> 
           getAddressOrBuilderList() {
        if (addressBuilder_ != null) {
          return addressBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(address_);
        }
      }
      /**
       * <code>repeated .employees.EmployeeProtobuf.Address address = 4;</code>
       */
      public tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf.Address.Builder addAddressBuilder() {
        return getAddressFieldBuilder().addBuilder(
            tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf.Address.getDefaultInstance());
      }
      /**
       * <code>repeated .employees.EmployeeProtobuf.Address address = 4;</code>
       */
      public tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf.Address.Builder addAddressBuilder(
          int index) {
        return getAddressFieldBuilder().addBuilder(
            index, tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf.Address.getDefaultInstance());
      }
      /**
       * <code>repeated .employees.EmployeeProtobuf.Address address = 4;</code>
       */
      public java.util.List<tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf.Address.Builder> 
           getAddressBuilderList() {
        return getAddressFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf.Address, tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf.Address.Builder, tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf.AddressOrBuilder> 
          getAddressFieldBuilder() {
        if (addressBuilder_ == null) {
          addressBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf.Address, tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf.Address.Builder, tcw.domain.protobuf.EmployeeProto.EmployeeProtobuf.AddressOrBuilder>(
                  address_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          address_ = null;
        }
        return addressBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:employees.EmployeeProtobuf)
    }

    static {
      defaultInstance = new EmployeeProtobuf(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:employees.EmployeeProtobuf)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_employees_EmployeeProtobuf_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_employees_EmployeeProtobuf_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_employees_EmployeeProtobuf_Address_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_employees_EmployeeProtobuf_Address_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016employee.proto\022\temployees\"\277\001\n\020Employee" +
      "Protobuf\022\022\n\nemployeeId\030\001 \002(\005\022\024\n\014employee" +
      "Name\030\002 \002(\t\022\022\n\ndepartment\030\003 \001(\t\0224\n\007addres" +
      "s\030\004 \003(\0132#.employees.EmployeeProtobuf.Add" +
      "ress\0327\n\007Address\022\016\n\006homeNo\030\001 \002(\005\022\016\n\006stree" +
      "t\030\002 \002(\t\022\014\n\004city\030\003 \002(\tB$\n\023tcw.domain.prot" +
      "obufB\rEmployeeProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_employees_EmployeeProtobuf_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_employees_EmployeeProtobuf_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_employees_EmployeeProtobuf_descriptor,
              new java.lang.String[] { "EmployeeId", "EmployeeName", "Department", "Address", });
          internal_static_employees_EmployeeProtobuf_Address_descriptor =
            internal_static_employees_EmployeeProtobuf_descriptor.getNestedTypes().get(0);
          internal_static_employees_EmployeeProtobuf_Address_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_employees_EmployeeProtobuf_Address_descriptor,
              new java.lang.String[] { "HomeNo", "Street", "City", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
