// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: employee.proto

package tcw.domain.protobuf;

public final class EmployeeProto {
  private EmployeeProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface EmployeeOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 employeeId = 1;
    /**
     * <code>required int64 employeeId = 1;</code>
     */
    boolean hasEmployeeId();
    /**
     * <code>required int64 employeeId = 1;</code>
     */
    long getEmployeeId();

    // required double salery = 2;
    /**
     * <code>required double salery = 2;</code>
     */
    boolean hasSalery();
    /**
     * <code>required double salery = 2;</code>
     */
    double getSalery();

    // required bool consultant = 3;
    /**
     * <code>required bool consultant = 3;</code>
     */
    boolean hasConsultant();
    /**
     * <code>required bool consultant = 3;</code>
     */
    boolean getConsultant();

    // required string employeeName = 4;
    /**
     * <code>required string employeeName = 4;</code>
     */
    boolean hasEmployeeName();
    /**
     * <code>required string employeeName = 4;</code>
     */
    java.lang.String getEmployeeName();
    /**
     * <code>required string employeeName = 4;</code>
     */
    com.google.protobuf.ByteString
        getEmployeeNameBytes();

    // repeated string departments = 5;
    /**
     * <code>repeated string departments = 5;</code>
     */
    java.util.List<java.lang.String>
    getDepartmentsList();
    /**
     * <code>repeated string departments = 5;</code>
     */
    int getDepartmentsCount();
    /**
     * <code>repeated string departments = 5;</code>
     */
    java.lang.String getDepartments(int index);
    /**
     * <code>repeated string departments = 5;</code>
     */
    com.google.protobuf.ByteString
        getDepartmentsBytes(int index);
  }
  /**
   * Protobuf type {@code employees.Employee}
   */
  public static final class Employee extends
      com.google.protobuf.GeneratedMessage
      implements EmployeeOrBuilder {
    // Use Employee.newBuilder() to construct.
    private Employee(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Employee(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Employee defaultInstance;
    public static Employee getDefaultInstance() {
      return defaultInstance;
    }

    public Employee getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Employee(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              employeeId_ = input.readInt64();
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              salery_ = input.readDouble();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              consultant_ = input.readBool();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              employeeName_ = input.readBytes();
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                departments_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000010;
              }
              departments_.add(input.readBytes());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          departments_ = new com.google.protobuf.UnmodifiableLazyStringList(departments_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return tcw.domain.protobuf.EmployeeProto.internal_static_employees_Employee_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tcw.domain.protobuf.EmployeeProto.internal_static_employees_Employee_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              tcw.domain.protobuf.EmployeeProto.Employee.class, tcw.domain.protobuf.EmployeeProto.Employee.Builder.class);
    }

    public static com.google.protobuf.Parser<Employee> PARSER =
        new com.google.protobuf.AbstractParser<Employee>() {
      public Employee parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Employee(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Employee> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int64 employeeId = 1;
    public static final int EMPLOYEEID_FIELD_NUMBER = 1;
    private long employeeId_;
    /**
     * <code>required int64 employeeId = 1;</code>
     */
    public boolean hasEmployeeId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 employeeId = 1;</code>
     */
    public long getEmployeeId() {
      return employeeId_;
    }

    // required double salery = 2;
    public static final int SALERY_FIELD_NUMBER = 2;
    private double salery_;
    /**
     * <code>required double salery = 2;</code>
     */
    public boolean hasSalery() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required double salery = 2;</code>
     */
    public double getSalery() {
      return salery_;
    }

    // required bool consultant = 3;
    public static final int CONSULTANT_FIELD_NUMBER = 3;
    private boolean consultant_;
    /**
     * <code>required bool consultant = 3;</code>
     */
    public boolean hasConsultant() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required bool consultant = 3;</code>
     */
    public boolean getConsultant() {
      return consultant_;
    }

    // required string employeeName = 4;
    public static final int EMPLOYEENAME_FIELD_NUMBER = 4;
    private java.lang.Object employeeName_;
    /**
     * <code>required string employeeName = 4;</code>
     */
    public boolean hasEmployeeName() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string employeeName = 4;</code>
     */
    public java.lang.String getEmployeeName() {
      java.lang.Object ref = employeeName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          employeeName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string employeeName = 4;</code>
     */
    public com.google.protobuf.ByteString
        getEmployeeNameBytes() {
      java.lang.Object ref = employeeName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        employeeName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated string departments = 5;
    public static final int DEPARTMENTS_FIELD_NUMBER = 5;
    private com.google.protobuf.LazyStringList departments_;
    /**
     * <code>repeated string departments = 5;</code>
     */
    public java.util.List<java.lang.String>
        getDepartmentsList() {
      return departments_;
    }
    /**
     * <code>repeated string departments = 5;</code>
     */
    public int getDepartmentsCount() {
      return departments_.size();
    }
    /**
     * <code>repeated string departments = 5;</code>
     */
    public java.lang.String getDepartments(int index) {
      return departments_.get(index);
    }
    /**
     * <code>repeated string departments = 5;</code>
     */
    public com.google.protobuf.ByteString
        getDepartmentsBytes(int index) {
      return departments_.getByteString(index);
    }

    private void initFields() {
      employeeId_ = 0L;
      salery_ = 0D;
      consultant_ = false;
      employeeName_ = "";
      departments_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasEmployeeId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSalery()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasConsultant()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEmployeeName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, employeeId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeDouble(2, salery_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBool(3, consultant_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getEmployeeNameBytes());
      }
      for (int i = 0; i < departments_.size(); i++) {
        output.writeBytes(5, departments_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, employeeId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, salery_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, consultant_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getEmployeeNameBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < departments_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(departments_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getDepartmentsList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static tcw.domain.protobuf.EmployeeProto.Employee parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tcw.domain.protobuf.EmployeeProto.Employee parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tcw.domain.protobuf.EmployeeProto.Employee parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tcw.domain.protobuf.EmployeeProto.Employee parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tcw.domain.protobuf.EmployeeProto.Employee parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static tcw.domain.protobuf.EmployeeProto.Employee parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static tcw.domain.protobuf.EmployeeProto.Employee parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static tcw.domain.protobuf.EmployeeProto.Employee parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static tcw.domain.protobuf.EmployeeProto.Employee parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static tcw.domain.protobuf.EmployeeProto.Employee parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(tcw.domain.protobuf.EmployeeProto.Employee prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code employees.Employee}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements tcw.domain.protobuf.EmployeeProto.EmployeeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return tcw.domain.protobuf.EmployeeProto.internal_static_employees_Employee_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return tcw.domain.protobuf.EmployeeProto.internal_static_employees_Employee_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                tcw.domain.protobuf.EmployeeProto.Employee.class, tcw.domain.protobuf.EmployeeProto.Employee.Builder.class);
      }

      // Construct using tcw.domain.protobuf.EmployeeProto.Employee.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        employeeId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        salery_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000002);
        consultant_ = false;
        bitField0_ = (bitField0_ & ~0x00000004);
        employeeName_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        departments_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return tcw.domain.protobuf.EmployeeProto.internal_static_employees_Employee_descriptor;
      }

      public tcw.domain.protobuf.EmployeeProto.Employee getDefaultInstanceForType() {
        return tcw.domain.protobuf.EmployeeProto.Employee.getDefaultInstance();
      }

      public tcw.domain.protobuf.EmployeeProto.Employee build() {
        tcw.domain.protobuf.EmployeeProto.Employee result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public tcw.domain.protobuf.EmployeeProto.Employee buildPartial() {
        tcw.domain.protobuf.EmployeeProto.Employee result = new tcw.domain.protobuf.EmployeeProto.Employee(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.employeeId_ = employeeId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.salery_ = salery_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.consultant_ = consultant_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.employeeName_ = employeeName_;
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          departments_ = new com.google.protobuf.UnmodifiableLazyStringList(
              departments_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.departments_ = departments_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof tcw.domain.protobuf.EmployeeProto.Employee) {
          return mergeFrom((tcw.domain.protobuf.EmployeeProto.Employee)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(tcw.domain.protobuf.EmployeeProto.Employee other) {
        if (other == tcw.domain.protobuf.EmployeeProto.Employee.getDefaultInstance()) return this;
        if (other.hasEmployeeId()) {
          setEmployeeId(other.getEmployeeId());
        }
        if (other.hasSalery()) {
          setSalery(other.getSalery());
        }
        if (other.hasConsultant()) {
          setConsultant(other.getConsultant());
        }
        if (other.hasEmployeeName()) {
          bitField0_ |= 0x00000008;
          employeeName_ = other.employeeName_;
          onChanged();
        }
        if (!other.departments_.isEmpty()) {
          if (departments_.isEmpty()) {
            departments_ = other.departments_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureDepartmentsIsMutable();
            departments_.addAll(other.departments_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasEmployeeId()) {
          
          return false;
        }
        if (!hasSalery()) {
          
          return false;
        }
        if (!hasConsultant()) {
          
          return false;
        }
        if (!hasEmployeeName()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        tcw.domain.protobuf.EmployeeProto.Employee parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (tcw.domain.protobuf.EmployeeProto.Employee) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 employeeId = 1;
      private long employeeId_ ;
      /**
       * <code>required int64 employeeId = 1;</code>
       */
      public boolean hasEmployeeId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 employeeId = 1;</code>
       */
      public long getEmployeeId() {
        return employeeId_;
      }
      /**
       * <code>required int64 employeeId = 1;</code>
       */
      public Builder setEmployeeId(long value) {
        bitField0_ |= 0x00000001;
        employeeId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 employeeId = 1;</code>
       */
      public Builder clearEmployeeId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        employeeId_ = 0L;
        onChanged();
        return this;
      }

      // required double salery = 2;
      private double salery_ ;
      /**
       * <code>required double salery = 2;</code>
       */
      public boolean hasSalery() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required double salery = 2;</code>
       */
      public double getSalery() {
        return salery_;
      }
      /**
       * <code>required double salery = 2;</code>
       */
      public Builder setSalery(double value) {
        bitField0_ |= 0x00000002;
        salery_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double salery = 2;</code>
       */
      public Builder clearSalery() {
        bitField0_ = (bitField0_ & ~0x00000002);
        salery_ = 0D;
        onChanged();
        return this;
      }

      // required bool consultant = 3;
      private boolean consultant_ ;
      /**
       * <code>required bool consultant = 3;</code>
       */
      public boolean hasConsultant() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required bool consultant = 3;</code>
       */
      public boolean getConsultant() {
        return consultant_;
      }
      /**
       * <code>required bool consultant = 3;</code>
       */
      public Builder setConsultant(boolean value) {
        bitField0_ |= 0x00000004;
        consultant_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool consultant = 3;</code>
       */
      public Builder clearConsultant() {
        bitField0_ = (bitField0_ & ~0x00000004);
        consultant_ = false;
        onChanged();
        return this;
      }

      // required string employeeName = 4;
      private java.lang.Object employeeName_ = "";
      /**
       * <code>required string employeeName = 4;</code>
       */
      public boolean hasEmployeeName() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string employeeName = 4;</code>
       */
      public java.lang.String getEmployeeName() {
        java.lang.Object ref = employeeName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          employeeName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string employeeName = 4;</code>
       */
      public com.google.protobuf.ByteString
          getEmployeeNameBytes() {
        java.lang.Object ref = employeeName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          employeeName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string employeeName = 4;</code>
       */
      public Builder setEmployeeName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        employeeName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string employeeName = 4;</code>
       */
      public Builder clearEmployeeName() {
        bitField0_ = (bitField0_ & ~0x00000008);
        employeeName_ = getDefaultInstance().getEmployeeName();
        onChanged();
        return this;
      }
      /**
       * <code>required string employeeName = 4;</code>
       */
      public Builder setEmployeeNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        employeeName_ = value;
        onChanged();
        return this;
      }

      // repeated string departments = 5;
      private com.google.protobuf.LazyStringList departments_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureDepartmentsIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          departments_ = new com.google.protobuf.LazyStringArrayList(departments_);
          bitField0_ |= 0x00000010;
         }
      }
      /**
       * <code>repeated string departments = 5;</code>
       */
      public java.util.List<java.lang.String>
          getDepartmentsList() {
        return java.util.Collections.unmodifiableList(departments_);
      }
      /**
       * <code>repeated string departments = 5;</code>
       */
      public int getDepartmentsCount() {
        return departments_.size();
      }
      /**
       * <code>repeated string departments = 5;</code>
       */
      public java.lang.String getDepartments(int index) {
        return departments_.get(index);
      }
      /**
       * <code>repeated string departments = 5;</code>
       */
      public com.google.protobuf.ByteString
          getDepartmentsBytes(int index) {
        return departments_.getByteString(index);
      }
      /**
       * <code>repeated string departments = 5;</code>
       */
      public Builder setDepartments(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureDepartmentsIsMutable();
        departments_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string departments = 5;</code>
       */
      public Builder addDepartments(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureDepartmentsIsMutable();
        departments_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string departments = 5;</code>
       */
      public Builder addAllDepartments(
          java.lang.Iterable<java.lang.String> values) {
        ensureDepartmentsIsMutable();
        super.addAll(values, departments_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string departments = 5;</code>
       */
      public Builder clearDepartments() {
        departments_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string departments = 5;</code>
       */
      public Builder addDepartmentsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureDepartmentsIsMutable();
        departments_.add(value);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:employees.Employee)
    }

    static {
      defaultInstance = new Employee(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:employees.Employee)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_employees_Employee_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_employees_Employee_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016employee.proto\022\temployees\"m\n\010Employee\022" +
      "\022\n\nemployeeId\030\001 \002(\003\022\016\n\006salery\030\002 \002(\001\022\022\n\nc" +
      "onsultant\030\003 \002(\010\022\024\n\014employeeName\030\004 \002(\t\022\023\n" +
      "\013departments\030\005 \003(\tB$\n\023tcw.domain.protobu" +
      "fB\rEmployeeProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_employees_Employee_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_employees_Employee_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_employees_Employee_descriptor,
              new java.lang.String[] { "EmployeeId", "Salery", "Consultant", "EmployeeName", "Departments", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
